### ISSUE TITLE
Missing add_dependencies in CMakefiles.txt

### ISSUE THREAD

**Issue by sguillaudeu** [ceptontech/cepton_ros#1]
The node failed to compile because SensorInformation.h wasn't found. Adding this line to CMakeLists.txt (at line 62 after add_library) fixed the issue:

`add_dependencies(cepton_ros cepton_ros_generate_messages_cpp)`

**Comment by spectralflight** [comment]
I checked the documentation, and it doesn't mention needing to add the dependency manually (http://wiki.ros.org/ROS/Tutorials/CreatingMsgAndSrv). Also, the node compiles on all my machines (Ubuntu 16.04, ROS Kinetic). Are you running an old version of ROS?

**Comment by sguillaudeu** [comment]
I'm using Kinetic on an nVidia Jetson TX2 board with an Arm64 processor. Not sure what's different, but the compiler complained about missing SensorInformation.h until I added the add_dependencies line.

**Comment by spectralflight** [comment]
Sorry for the delay. I just tested compiling and running the driver on our Jetson TX2 board, and it compiles just fine. Maybe we are running different versions of CMAKE. I'll just add the line.
